print(r" ____  ____  _____   ____  ____  ___  ____    _____  _  _  ____ ")
print(r"(  _ \(  _ \(  _  ) (_  _)( ___)/ __)(_  _)  (  _  )( \( )( ___)")
print(r" )___/ )   / )(_)( .-_)(   )__)( (__   )(     )(_)(  )  (  )__) ")
print(r"(__)  (_)\_)(_____)\____) (____)\___) (__)   (_____)(_)\_)(____)")
print("Hi There!")
name = input("What is your name?")
print(f"Wow, {name} is my name too")
print(f"well {name} let's talk about school!")
school = input("where do you go to school?")
print(f"No way, I know who someone goes to {school}")
teacher = input(f"Who is your favorite teacher at {school}?")
print("Cool!!!")
teach = input(f"What does {teacher} teach???")
input(f"well, is that your favorite class or just your favorite teacher?")
print("Cool")
hru = input(f"well {name} how are you today")
print(f"I am also feeling {hru}")
grade = input(f"I forgot to ask but what grade are you in {name}?")
input(f"wait, you are really in {grade} ???!!!!")
print("sameeeee")
fave = input(f"what is your fave thing about {grade} ????")
print(f"wait, u also like {fave} the most, cuz sameeeeee")
print("o my gosh, we are twinning!!!!!!")
print("well...")
print("I have to go do homework :(")
print(r" ___  _  _  ____ ")
print(r"/ __)( \/ )(_  _)")
print(r"\__ \ \  /   )(  ")
print(r"(___/ (__)  (__) ")